import { SeatPropertyTypes } from "./type";

const allSeats: (SeatPropertyTypes | null)[][] = [
  [
    { id: "1A", status: "available" },
    { id: "1B", status: "occupied" },
    { id: "1C", status: "available" },
    null,
    { id: "1D", status: "unavailable" },
    { id: "1E", status: "available" },
    { id: "1F", status: "vip" },
  ],
  [
    { id: "2A", status: "vip" },
    { id: "2B", status: "available" },
    { id: "2C", status: "available" },
    null,
    { id: "2D", status: "unavailable" },
    { id: "2E", status: "available" },
    { id: "2F", status: "vip" },
  ],
  [
    { id: "3A", status: "occupied" },
    { id: "3B", status: "occupied" },
    { id: "3C", status: "available" },
    null,
    { id: "3D", status: "available" },
    { id: "3E", status: "available" },
    { id: "3F", status: "unavailable" },
  ],
  [
    { id: "4A", status: "available" },
    { id: "4B", status: "available" },
    { id: "4C", status: "unavailable" },
    null,
    { id: "4D", status: "available" },
    { id: "4E", status: "occupied" },
    { id: "4F", status: "available" },
  ],
  [
    { id: "5A", status: "unavailable" },
    { id: "5B", status: "available" },
    { id: "5C", status: "available" },
    null,
    { id: "5D", status: "unavailable" },
    { id: "5E", status: "available" },
    { id: "5F", status: "occupied" },
  ],
  [
    { id: "6A", status: "available" },
    { id: "6B", status: "unavailable" },
    { id: "6C", status: "occupied" },
    null,
    { id: "6D", status: "available" },
    { id: "6E", status: "available" },
    { id: "6F", status: "available" },
  ],
  [
    { id: "7A", status: "available" },
    { id: "7B", status: "available" },
    { id: "7C", status: "available" },
    null,
    { id: "7D", status: "unavailable" },
    { id: "7E", status: "occupied" },
    { id: "7F", status: "available" },
  ],
  [
    { id: "8A", status: "available" },
    { id: "8B", status: "unavailable" },
    { id: "8C", status: "available" },
    null,
    { id: "8D", status: "available" },
    { id: "8E", status: "available" },
    { id: "8F", status: "occupied" },
  ],
  [
    { id: "9A", status: "occupied" },
    { id: "9B", status: "available" },
    { id: "9C", status: "occupied" },
    null,
    { id: "9D", status: "available" },
    { id: "9E", status: "available" },
    { id: "9F", status: "unavailable" },
  ],
  [
    { id: "10A", status: "available" },
    { id: "10B", status: "unavailable" },
    { id: "10C", status: "available" },
    null,
    { id: "10D", status: "occupied" },
    { id: "10E", status: "available" },
    { id: "10F", status: "available" },
  ],
  [
    { id: "11A", status: "available" },
    { id: "11B", status: "available" },
    { id: "11C", status: "unavailable" },
    null,
    { id: "11D", status: "available" },
    { id: "11E", status: "occupied" },
    { id: "11F", status: "available" },
  ],
  [
    { id: "12A", status: "available" },
    { id: "12B", status: "occupied" },
    { id: "12C", status: "available" },
    null,
    { id: "12D", status: "available" },
    { id: "12E", status: "unavailable" },
    { id: "12F", status: "available" },
  ],
  [
    { id: "13A", status: "unavailable" },
    { id: "13B", status: "available" },
    { id: "13C", status: "available" },
    null,
    { id: "13D", status: "occupied" },
    { id: "13E", status: "available" },
    { id: "13F", status: "available" },
  ],
  [
    { id: "14A", status: "available" },
    { id: "14B", status: "unavailable" },
    { id: "14C", status: "available" },
    null,
    { id: "14D", status: "available" },
    { id: "14E", status: "occupied" },
    { id: "14F", status: "available" },
  ],
  [
    { id: "15A", status: "available" },
    { id: "15B", status: "occupied" },
    { id: "15C", status: "available" },
    null,
    { id: "15D", status: "available" },
    { id: "15E", status: "unavailable" },
    { id: "15F", status: "available" },
  ],
  [
    { id: "16A", status: "available" },
    { id: "16B", status: "available" },
    { id: "16C", status: "unavailable" },
    null,
    { id: "16D", status: "occupied" },
    { id: "16E", status: "available" },
    { id: "16F", status: "available" },
  ],
  [
    { id: "17A", status: "unavailable" },
    { id: "17B", status: "occupied" },
    { id: "17C", status: "available" },
    null,
    { id: "17D", status: "unavailable" },
    { id: "17E", status: "available" },
    { id: "17F", status: "occupied" },
  ],
  [
    { id: "18A", status: "available" },
    { id: "18B", status: "occupied" },
    { id: "18C", status: "available" },
    null,
    { id: "18D", status: "available" },
    { id: "18E", status: "available" },
    { id: "18F", status: "unavailable" },
  ],
  [
    { id: "19A", status: "available" },
    { id: "19B", status: "available" },
    { id: "19C", status: "available" },
    null,
    { id: "19D", status: "occupied" },
    { id: "19E", status: "available" },
    { id: "19F", status: "unavailable" },
  ],
  [
    { id: "20A", status: "occupied" },
    { id: "20B", status: "unavailable" },
    { id: "20C", status: "available" },
    null,
    { id: "20D", status: "available" },
    { id: "20E", status: "available" },
    { id: "20F", status: "available" },
  ],
  [
    { id: "21A", status: "available" },
    { id: "21B", status: "occupied" },
    { id: "21C", status: "available" },
    null,
    { id: "21D", status: "unavailable" },
    { id: "21E", status: "available" },
    { id: "21F", status: "available" },
  ],
  [
    { id: "22A", status: "available" },
    { id: "22B", status: "unavailable" },
    { id: "22C", status: "available" },
    null,
    { id: "22D", status: "occupied" },
    { id: "22E", status: "available" },
    { id: "22F", status: "available" },
  ],
  [
    { id: "23A", status: "available" },
    { id: "23B", status: "available" },
    { id: "23C", status: "available" },
    null,
    { id: "23D", status: "unavailable" },
    { id: "23E", status: "occupied" },
    { id: "23F", status: "available" },
  ],
  [
    { id: "24A", status: "unavailable" },
    { id: "24B", status: "available" },
    { id: "24C", status: "available" },
    null,
    { id: "24D", status: "available" },
    { id: "24E", status: "available" },
    { id: "24F", status: "unavailable" },
  ],
  [
    { id: "25A", status: "occupied" },
    { id: "25B", status: "available" },
    { id: "25C", status: "available" },
    null,
    { id: "25D", status: "unavailable" },
    { id: "25E", status: "occupied" },
    { id: "25F", status: "available" },
  ],
];

export default allSeats;
