import { SeatPropertyTypes } from "./type";

const allSeats: (SeatPropertyTypes | null)[][] = [
  [
    {
      id: "1A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "1B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "1C",
      status: "available",
      unsuitableForHandicap: true,
      armTrayLeft: true,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "1D",
      status: "unavailable",
      unsuitableForHandicap: true,
      armTrayLeft: true,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "1E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "1F",
      status: "vip",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "2A",
      status: "vip",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "2B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "2C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: true,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "2D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "2E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "2F",
      status: "vip",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "3A",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "3B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "3C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: true,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "3D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "3E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "3F",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "4A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "4B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "4C",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "4D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "4E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "4F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "5A",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "5B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "5C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "5D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "5E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "5F",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "6A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "6B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "6C",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "6D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "6E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "6F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "7A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "7B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "7C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "7D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "7E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "7F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "8A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "8B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "8C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "8D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "8E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "8F",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "9A",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "9B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "9C",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "9D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "9E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "9F",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "10A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "10B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "10C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "10D",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "10E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "10F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "11A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "11B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "11C",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    null,
    {
      id: "11D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "11E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "11F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
  ],
  [
    {
      id: "12A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: true,
    },
    {
      id: "12B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "12C",
      status: "available",
      unsuitableForHandicap: true,
      armTrayLeft: false,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    null,
    {
      id: "12D",
      status: "available",
      unsuitableForHandicap: true,
      armTrayLeft: true,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "12E",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "12F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: true,
      hideSeat: true,
    },
  ],
  [
    {
      id: "13A",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "13B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "13C",
      status: "available",
      unsuitableForHandicap: true,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "13D",
      status: "occupied",
      unsuitableForHandicap: true,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "13E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: true,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "13F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: true,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: true,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "14A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "14B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "14C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "14D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "14E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "14F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "15A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "15B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "15C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "15D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "15E",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "15F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "16A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "16B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "16C",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "16D",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "16E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "16F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "17A",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "17B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "17C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "17D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "17E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "17F",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "18A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "18B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "18C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "18D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "18E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "18F",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "19A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "19B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "19C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "19D",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "19E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "19F",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "20A",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "20B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "20C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "20D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "20E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "20F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "21A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "21B",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "21C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "21D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "21E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "21F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "22A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "22B",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "22C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "22D",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "22E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "22F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "23A",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "23B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "23C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: true,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "23D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "23E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "23F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "24A",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "24B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "24C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: true,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    null,
    {
      id: "24D",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "24E",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
    {
      id: "24F",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: false,
      hideSeat: false,
    },
  ],
  [
    {
      id: "25A",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "25B",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "25C",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: true,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    null,
    {
      id: "25D",
      status: "unavailable",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "25E",
      status: "occupied",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
    {
      id: "25F",
      status: "available",
      unsuitableForHandicap: false,
      armTrayLeft: false,
      armTrayRight: false,
      babyHammock: false,
      handicapArmRest: false,
      noBreakOver: false,
      limitedRecline: false,
      noRecline: true,
      hideSeat: false,
    },
  ],
];

export default allSeats;
